### ISSUE TITLE
same ore

### ISSUE THREAD

**Issue by ghost** [Drazuam/create_infinidrill#7]
deepslate ore not count with normal ore
normal oreore not count with deepslate
![image](https://user-images.githubusercontent.com/51057953/180693147-03301934-aaa8-4ae8-b191-eb578a07ed23.png)
![image](https://user-images.githubusercontent.com/51057953/180693203-6ac557f4-7483-46b1-a310-e3bc71adeea7.png)

**Comment by Drazuam** [comment]
This is intended behavior.  It checks for ore deposits, not ore types.  A way of implementing your expected behavior is possible, but not simple - it would require a lot of configuration by the modpack developer.  It could add some value as an option, especially in gregtech-related packs...  So I'll consider it.  I think there's value to be gained here.
